# ====================================================================================

version: '3'

services:

# ====================================================================================

  # Активирует докер файл для fastapi
  fastapi:
      build: 
        context: .
        dockerfile: fastapi.Dockerfile
      ports:
        - "8000:8000"
      depends_on:
      - redis
# ====================================================================================

  # Активирует докер файл для telegram_bot
  telegram_bot:
    build: 
      context: .
      dockerfile: telegram_bot.Dockerfile
    ports:
      - "8080:8080" # Порт для взаимодействия с телеграм-ботом

# ====================================================================================

  # Активирует докер файл для Redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

# ====================================================================================

# 
 # rabbitmq:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5672:5672" # Порт для AMQP протокола
  #     - "15672:15672" # Порт для веб-интерфейса управления
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   volumes:
  #     - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
